Traceback (most recent call last):
  File "/Users/aileen/Library/Caches/pypoetry/virtualenvs/cuyh3470-cipher-93VOqk-C-py3.9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/aileen/Library/Caches/pypoetry/virtualenvs/cuyh3470-cipher-93VOqk-C-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/aileen/Library/Caches/pypoetry/virtualenvs/cuyh3470-cipher-93VOqk-C-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/aileen/Library/Caches/pypoetry/virtualenvs/cuyh3470-cipher-93VOqk-C-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/aileen/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/aileen/Library/Caches/pypoetry/virtualenvs/cuyh3470-cipher-93VOqk-C-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/aileen/Library/Caches/pypoetry/virtualenvs/cuyh3470-cipher-93VOqk-C-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/aileen/Library/Caches/pypoetry/virtualenvs/cuyh3470-cipher-93VOqk-C-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import cuyh3470_cipher

print(cuyh3470_cipher.__version__)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn [1], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mcuyh3470_cipher[39;00m
[0;32m----> 3[0m [38;5;28mprint[39m([43mcuyh3470_cipher[49m[38;5;241;43m.[39;49m[43m__version__[49m)

[0;31mAttributeError[0m: module 'cuyh3470_cipher' has no attribute '__version__'
AttributeError: module 'cuyh3470_cipher' has no attribute '__version__'

